### ISSUE TITLE
Component Request - GalleryList - 2.5hrs

### ISSUE THREAD

**Issue by drewbaker** [funkhaus/factory#11]
## Component Description

This component is used to display a list of names (as links) that on hover show an image. Sometimes the names are in columns, sometimes they are in a comma separated sentence.

- Min-height of 75vh
- When `column` variant, If more than 7 names, go to 2 columns, if more than 14 names, go to 3 columns. 
- Other variant is `comma`

## Design

Please also see attached screenshots for quick reference.

- Desktop: 
    - https://xd.adobe.com/view/1b5027a3-98f1-48ce-7968-22ffdcb8d2fe-6d61/screen/ab993f11-8b66-479f-919a-384bc9f98cd4/Rock-Paper-Scissors-Talent-Roster
    - https://xd.adobe.com/view/1b5027a3-98f1-48ce-7968-22ffdcb8d2fe-6d61/screen/71cde655-156e-4ad1-be2a-70c7b60fabea/Elastic-About (3rd of way down page)
     - https://xd.adobe.com/view/1b5027a3-98f1-48ce-7968-22ffdcb8d2fe-6d61/screen/975ac09d-f144-489c-8940-ea4ddc0d5039/Elastic-Landing (at bottom of page)

- Mobile: https://xd.adobe.com/view/fdfa03f9-36db-4e2f-5200-19ec6adc2d57-8bcb/screen/f490d130-e801-4c62-b211-f09c3aa8856c/About-Elastic

On mobile, no hover state (so no images loaded, just link). On mobile, go to one column of names. Comma variant just wraps (see designs).

Email drew@funkhaus.us for the design password.

## Props

```
props: {
    items: {
        // Mock: api.pages (each item contains the name, and the image)
        type: Array,
        default: () => []
    },
    title: {
        // Only used on the sentence variant 
        type: String,
        default: "" 
    },
    variant: {
        type: String,
        default: "column" // Or comma
    },
    date: {
        type: String,
        default: ""
    }
}
```

## Dev Tips

1. In column mode, use `--color-company` for the font color, other wise in comma mode use `--color-black`.
2. Add `is-variant-${this.variant}` as a class, and use that to style variants differently I think.

## Required components

1. `wp-image` for the background hover image
1. The `@/utils/tools.js` contains a sortColumns function that might help with the names. Or CSS flexbox? 

## Time & Budget

Time estimate: 2hrs
Budget: $250

![Screen Shot 2020-06-26 at 7 04 00 PM](https://user-images.githubusercontent.com/475015/85912488-ba56d980-b7e1-11ea-9896-fa9a370ec675.png)
![Screen Shot 2020-06-26 at 7 04 42 PM](https://user-images.githubusercontent.com/475015/85912490-bb880680-b7e1-11ea-9950-234685b57ddb.png)
![Screen Shot 2020-06-26 at 7 07 49 PM](https://user-images.githubusercontent.com/475015/85912491-bc209d00-b7e1-11ea-8740-88eaa193acf5.png)
![Screen Shot 2020-06-26 at 7 03 52 PM](https://user-images.githubusercontent.com/475015/85912498-c93d8c00-b7e1-11ea-9f1a-a3a2266f25e6.png)

**Comment by ibanzajoe** [comment]
I want this

**Comment by drewbaker** [comment]
Approved! Any questions, let me know.
