### ISSUE TITLE
Component Request - BannerHighlight - 0.5hrs

### ISSUE THREAD

**Issue by drewbaker** [funkhaus/factory#9]
## Component Description

A 80vh height banner with an image and a link.

The image will be uploaded with some shadow on it, so no need to worry about putting opacity or filters on the image. 

Note hover state of the explore prompt (arrow moves sideways).

## Design

Please also see attached screenshots for quick reference.

- Desktop: https://xd.adobe.com/view/1b5027a3-98f1-48ce-7968-22ffdcb8d2fe-6d61/screen/84141268-0730-442d-b88f-96480f3fadd2/Make-Make-Landing-4

If no mobile designs provided, please use your best judgment for responsiveness.

Email drew@funkhaus.us for the design password.

## Props

```
props: {
    image: {
        // Mock: api.image
        type: Object,
        default: () => {}
    },
    text: {
        type: String,
        default: "Originals"
    },
    prompt: {
        type: String,
        default: "Explore"
    },
    to: {
        type: String,
        default: ""
    }
}
```

## Required components

1. `wp-image` is used for the background image
1. You'll need to put a `nuxt-link` around the text and prompt. Please add 20px to this to make it easy to click.
1. Arrow should be an SVG

## Time & Budget

Time estimate: 0.5hrs
Budget: $50

![Screen Shot 2020-06-26 at 6 24 38 PM](https://user-images.githubusercontent.com/475015/85911476-5250c500-b7da-11ea-9d1e-e9ae00112067.png)

**Comment by uptownhr** [comment]
Would like to take this one.

**Comment by drewbaker** [comment]
Approved! Assigned to @uptownhr.
